//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaServerService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetFileRequest", Namespace="http://schemas.datacontract.org/2004/07/ebsco.svc.mediaserver.contract.messages")]
    public partial class GetFileRequest : object
    {
        
        private string GuidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Guid
        {
            get
            {
                return this.GuidField;
            }
            set
            {
                this.GuidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetFileResponse", Namespace="http://schemas.datacontract.org/2004/07/ebsco.svc.mediaserver.contract.messages")]
    public partial class GetFileResponse : object
    {
        
        private MediaServerService.MediaFile FileField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MediaServerService.MediaFile File
        {
            get
            {
                return this.FileField;
            }
            set
            {
                this.FileField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MediaFile", Namespace="http://schemas.datacontract.org/2004/07/ebsco.svc.mediaserver.contract.dto")]
    public partial class MediaFile : object
    {
        
        private byte[] ContentsField;
        
        private System.DateTime DateCreatedField;
        
        private System.DateTime DateModifiedField;
        
        private string FileGuidField;
        
        private string FileNameField;
        
        private string MimeTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Contents
        {
            get
            {
                return this.ContentsField;
            }
            set
            {
                this.ContentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated
        {
            get
            {
                return this.DateCreatedField;
            }
            set
            {
                this.DateCreatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateModified
        {
            get
            {
                return this.DateModifiedField;
            }
            set
            {
                this.DateModifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileGuid
        {
            get
            {
                return this.FileGuidField;
            }
            set
            {
                this.FileGuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MimeType
        {
            get
            {
                return this.MimeTypeField;
            }
            set
            {
                this.MimeTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetProcessedFileRequest", Namespace="http://schemas.datacontract.org/2004/07/ebsco.svc.mediaserver.contract.messages")]
    public partial class GetProcessedFileRequest : object
    {
        
        private string GuidField;
        
        private MediaServerService.ActionMetadata[] MetadataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Guid
        {
            get
            {
                return this.GuidField;
            }
            set
            {
                this.GuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MediaServerService.ActionMetadata[] Metadata
        {
            get
            {
                return this.MetadataField;
            }
            set
            {
                this.MetadataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActionMetadata", Namespace="http://schemas.datacontract.org/2004/07/ebsco.svc.mediaserver.contract.dto")]
    public partial class ActionMetadata : object
    {
        
        private int ActionIdField;
        
        private System.Collections.Generic.KeyValuePair<string, string>[] ActionPropertiesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActionId
        {
            get
            {
                return this.ActionIdField;
            }
            set
            {
                this.ActionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] ActionProperties
        {
            get
            {
                return this.ActionPropertiesField;
            }
            set
            {
                this.ActionPropertiesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetProcessedFileResponse", Namespace="http://schemas.datacontract.org/2004/07/ebsco.svc.mediaserver.contract.messages")]
    public partial class GetProcessedFileResponse : object
    {
        
        private MediaServerService.MediaFile FileField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MediaServerService.MediaFile File
        {
            get
            {
                return this.FileField;
            }
            set
            {
                this.FileField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddFileRequest", Namespace="http://schemas.datacontract.org/2004/07/ebsco.svc.mediaserver.contract.messages")]
    public partial class AddFileRequest : object
    {
        
        private MediaServerService.MediaFile FileField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MediaServerService.MediaFile File
        {
            get
            {
                return this.FileField;
            }
            set
            {
                this.FileField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddFileResponse", Namespace="http://schemas.datacontract.org/2004/07/ebsco.svc.mediaserver.contract.messages")]
    public partial class AddFileResponse : object
    {
        
        private string GuidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Guid
        {
            get
            {
                return this.GuidField;
            }
            set
            {
                this.GuidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateFileRequest", Namespace="http://schemas.datacontract.org/2004/07/ebsco.svc.mediaserver.contract.messages")]
    public partial class UpdateFileRequest : object
    {
        
        private MediaServerService.MediaFile FileField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MediaServerService.MediaFile File
        {
            get
            {
                return this.FileField;
            }
            set
            {
                this.FileField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateFileResponse", Namespace="http://schemas.datacontract.org/2004/07/ebsco.svc.mediaserver.contract.messages")]
    public partial class UpdateFileResponse : object
    {
        
        private bool WasSuccessfulField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool WasSuccessful
        {
            get
            {
                return this.WasSuccessfulField;
            }
            set
            {
                this.WasSuccessfulField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteFileRequest", Namespace="http://schemas.datacontract.org/2004/07/ebsco.svc.mediaserver.contract.messages")]
    public partial class DeleteFileRequest : object
    {
        
        private string GuidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Guid
        {
            get
            {
                return this.GuidField;
            }
            set
            {
                this.GuidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteFileResponse", Namespace="http://schemas.datacontract.org/2004/07/ebsco.svc.mediaserver.contract.messages")]
    public partial class DeleteFileResponse : object
    {
        
        private bool WasSuccessfulField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool WasSuccessful
        {
            get
            {
                return this.WasSuccessfulField;
            }
            set
            {
                this.WasSuccessfulField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurgeFileRequest", Namespace="http://schemas.datacontract.org/2004/07/ebsco.svc.mediaserver.contract.messages")]
    public partial class PurgeFileRequest : object
    {
        
        private string GuidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Guid
        {
            get
            {
                return this.GuidField;
            }
            set
            {
                this.GuidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurgeFileResponse", Namespace="http://schemas.datacontract.org/2004/07/ebsco.svc.mediaserver.contract.messages")]
    public partial class PurgeFileResponse : object
    {
        
        private bool WasSuccessfulField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool WasSuccessful
        {
            get
            {
                return this.WasSuccessfulField;
            }
            set
            {
                this.WasSuccessfulField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMimeTypeRequest", Namespace="http://schemas.datacontract.org/2004/07/ebsco.svc.mediaserver.contract.messages")]
    public partial class GetMimeTypeRequest : object
    {
        
        private string FilenameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filename
        {
            get
            {
                return this.FilenameField;
            }
            set
            {
                this.FilenameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMimeTypeResponse", Namespace="http://schemas.datacontract.org/2004/07/ebsco.svc.mediaserver.contract.messages")]
    public partial class GetMimeTypeResponse : object
    {
        
        private string MimeTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MimeType
        {
            get
            {
                return this.MimeTypeField;
            }
            set
            {
                this.MimeTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddValidHostRequest", Namespace="http://schemas.datacontract.org/2004/07/ebsco.svc.mediaserver.contract.messages")]
    public partial class AddValidHostRequest : object
    {
        
        private string HostField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Host
        {
            get
            {
                return this.HostField;
            }
            set
            {
                this.HostField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddValidHostResponse", Namespace="http://schemas.datacontract.org/2004/07/ebsco.svc.mediaserver.contract.messages")]
    public partial class AddValidHostResponse : object
    {
        
        private bool WasSuccessfulField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool WasSuccessful
        {
            get
            {
                return this.WasSuccessfulField;
            }
            set
            {
                this.WasSuccessfulField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteValidHostRequest", Namespace="http://schemas.datacontract.org/2004/07/ebsco.svc.mediaserver.contract.messages")]
    public partial class DeleteValidHostRequest : object
    {
        
        private string HostField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Host
        {
            get
            {
                return this.HostField;
            }
            set
            {
                this.HostField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteValidHostResponse", Namespace="http://schemas.datacontract.org/2004/07/ebsco.svc.mediaserver.contract.messages")]
    public partial class DeleteValidHostResponse : object
    {
        
        private bool WasSuccessfulField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool WasSuccessful
        {
            get
            {
                return this.WasSuccessfulField;
            }
            set
            {
                this.WasSuccessfulField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IsValidHostRequest", Namespace="http://schemas.datacontract.org/2004/07/ebsco.svc.mediaserver.contract.messages")]
    public partial class IsValidHostRequest : object
    {
        
        private string HostField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Host
        {
            get
            {
                return this.HostField;
            }
            set
            {
                this.HostField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IsValidHostResponse", Namespace="http://schemas.datacontract.org/2004/07/ebsco.svc.mediaserver.contract.messages")]
    public partial class IsValidHostResponse : object
    {
        
        private bool IsValidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsValid
        {
            get
            {
                return this.IsValidField;
            }
            set
            {
                this.IsValidField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MediaServerService.IMediaServerService")]
    public interface IMediaServerService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaServerService/GetFile", ReplyAction="http://tempuri.org/IMediaServerService/GetFileResponse")]
        System.Threading.Tasks.Task<MediaServerService.GetFileResponse> GetFileAsync(MediaServerService.GetFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaServerService/GetProcessedFile", ReplyAction="http://tempuri.org/IMediaServerService/GetProcessedFileResponse")]
        System.Threading.Tasks.Task<MediaServerService.GetProcessedFileResponse> GetProcessedFileAsync(MediaServerService.GetProcessedFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaServerService/AddFile", ReplyAction="http://tempuri.org/IMediaServerService/AddFileResponse")]
        System.Threading.Tasks.Task<MediaServerService.AddFileResponse> AddFileAsync(MediaServerService.AddFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaServerService/UpdateFile", ReplyAction="http://tempuri.org/IMediaServerService/UpdateFileResponse")]
        System.Threading.Tasks.Task<MediaServerService.UpdateFileResponse> UpdateFileAsync(MediaServerService.UpdateFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaServerService/DeleteFile", ReplyAction="http://tempuri.org/IMediaServerService/DeleteFileResponse")]
        System.Threading.Tasks.Task<MediaServerService.DeleteFileResponse> DeleteFileAsync(MediaServerService.DeleteFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaServerService/PurgeFile", ReplyAction="http://tempuri.org/IMediaServerService/PurgeFileResponse")]
        System.Threading.Tasks.Task<MediaServerService.PurgeFileResponse> PurgeFileAsync(MediaServerService.PurgeFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaServerService/GetMimeType", ReplyAction="http://tempuri.org/IMediaServerService/GetMimeTypeResponse")]
        System.Threading.Tasks.Task<MediaServerService.GetMimeTypeResponse> GetMimeTypeAsync(MediaServerService.GetMimeTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaServerService/AddValidHost", ReplyAction="http://tempuri.org/IMediaServerService/AddValidHostResponse")]
        System.Threading.Tasks.Task<MediaServerService.AddValidHostResponse> AddValidHostAsync(MediaServerService.AddValidHostRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaServerService/DeleteValidHost", ReplyAction="http://tempuri.org/IMediaServerService/DeleteValidHostResponse")]
        System.Threading.Tasks.Task<MediaServerService.DeleteValidHostResponse> DeleteValidHostAsync(MediaServerService.DeleteValidHostRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaServerService/IsValidHost", ReplyAction="http://tempuri.org/IMediaServerService/IsValidHostResponse")]
        System.Threading.Tasks.Task<MediaServerService.IsValidHostResponse> IsValidHostAsync(MediaServerService.IsValidHostRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaServerService/GetFileStream", ReplyAction="http://tempuri.org/IMediaServerService/GetFileStreamResponse")]
        System.Threading.Tasks.Task<MediaServerService.GetFileStreamResponse> GetFileStreamAsync(MediaServerService.GetFileStreamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaServerService/AddFileStream", ReplyAction="http://tempuri.org/IMediaServerService/AddFileStreamResponse")]
        System.Threading.Tasks.Task<MediaServerService.AddFileStreamResponse> AddFileStreamAsync(MediaServerService.AddFileStreamRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileStreamRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileStreamRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Guid;
        
        public GetFileStreamRequest()
        {
        }
        
        public GetFileStreamRequest(string Guid)
        {
            this.Guid = Guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileStreamResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileStreamResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public System.DateTime DateCreated;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public System.DateTime DateModified;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileGuid;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string MimeType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public byte[] Contents;
        
        public GetFileStreamResponse()
        {
        }
        
        public GetFileStreamResponse(System.DateTime DateCreated, System.DateTime DateModified, string FileGuid, string FileName, string MimeType, byte[] Contents)
        {
            this.DateCreated = DateCreated;
            this.DateModified = DateModified;
            this.FileGuid = FileGuid;
            this.FileName = FileName;
            this.MimeType = MimeType;
            this.Contents = Contents;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddFileStreamRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddFileStreamRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public System.DateTime DateCreated;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public System.DateTime DateModified;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileGuid;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string MimeType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public byte[] Contents;
        
        public AddFileStreamRequest()
        {
        }
        
        public AddFileStreamRequest(System.DateTime DateCreated, System.DateTime DateModified, string FileGuid, string FileName, string MimeType, byte[] Contents)
        {
            this.DateCreated = DateCreated;
            this.DateModified = DateModified;
            this.FileGuid = FileGuid;
            this.FileName = FileName;
            this.MimeType = MimeType;
            this.Contents = Contents;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddFileStreamResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddFileStreamResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Guid;
        
        public AddFileStreamResponse()
        {
        }
        
        public AddFileStreamResponse(string Guid)
        {
            this.Guid = Guid;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface IMediaServerServiceChannel : MediaServerService.IMediaServerService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class MediaServerServiceClient : System.ServiceModel.ClientBase<MediaServerService.IMediaServerService>, MediaServerService.IMediaServerService
    {
        
        public MediaServerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<MediaServerService.GetFileResponse> GetFileAsync(MediaServerService.GetFileRequest request)
        {
            return base.Channel.GetFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<MediaServerService.GetProcessedFileResponse> GetProcessedFileAsync(MediaServerService.GetProcessedFileRequest request)
        {
            return base.Channel.GetProcessedFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<MediaServerService.AddFileResponse> AddFileAsync(MediaServerService.AddFileRequest request)
        {
            return base.Channel.AddFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<MediaServerService.UpdateFileResponse> UpdateFileAsync(MediaServerService.UpdateFileRequest request)
        {
            return base.Channel.UpdateFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<MediaServerService.DeleteFileResponse> DeleteFileAsync(MediaServerService.DeleteFileRequest request)
        {
            return base.Channel.DeleteFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<MediaServerService.PurgeFileResponse> PurgeFileAsync(MediaServerService.PurgeFileRequest request)
        {
            return base.Channel.PurgeFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<MediaServerService.GetMimeTypeResponse> GetMimeTypeAsync(MediaServerService.GetMimeTypeRequest request)
        {
            return base.Channel.GetMimeTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<MediaServerService.AddValidHostResponse> AddValidHostAsync(MediaServerService.AddValidHostRequest request)
        {
            return base.Channel.AddValidHostAsync(request);
        }
        
        public System.Threading.Tasks.Task<MediaServerService.DeleteValidHostResponse> DeleteValidHostAsync(MediaServerService.DeleteValidHostRequest request)
        {
            return base.Channel.DeleteValidHostAsync(request);
        }
        
        public System.Threading.Tasks.Task<MediaServerService.IsValidHostResponse> IsValidHostAsync(MediaServerService.IsValidHostRequest request)
        {
            return base.Channel.IsValidHostAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MediaServerService.GetFileStreamResponse> MediaServerService.IMediaServerService.GetFileStreamAsync(MediaServerService.GetFileStreamRequest request)
        {
            return base.Channel.GetFileStreamAsync(request);
        }
        
        public System.Threading.Tasks.Task<MediaServerService.GetFileStreamResponse> GetFileStreamAsync(string Guid)
        {
            MediaServerService.GetFileStreamRequest inValue = new MediaServerService.GetFileStreamRequest();
            inValue.Guid = Guid;
            return ((MediaServerService.IMediaServerService)(this)).GetFileStreamAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MediaServerService.AddFileStreamResponse> MediaServerService.IMediaServerService.AddFileStreamAsync(MediaServerService.AddFileStreamRequest request)
        {
            return base.Channel.AddFileStreamAsync(request);
        }
        
        public System.Threading.Tasks.Task<MediaServerService.AddFileStreamResponse> AddFileStreamAsync(System.DateTime DateCreated, System.DateTime DateModified, string FileGuid, string FileName, string MimeType, byte[] Contents)
        {
            MediaServerService.AddFileStreamRequest inValue = new MediaServerService.AddFileStreamRequest();
            inValue.DateCreated = DateCreated;
            inValue.DateModified = DateModified;
            inValue.FileGuid = FileGuid;
            inValue.FileName = FileName;
            inValue.MimeType = MimeType;
            inValue.Contents = Contents;
            return ((MediaServerService.IMediaServerService)(this)).AddFileStreamAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
